style = "conventional"
subject_capitalized = false
allowed_types = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "refactor", "style", "test"]
allowed_scopes = ["db", "deps", "devcontainer", "docker", "server", "web"]
